export const GET_MOVIE_START = "GET_MOVIE_START";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE";
export const NOMINATE_MOVIE = "NOMINATE_MOVIE";
export const SHOW_NOMINATION_BANNER = "SHOW_NOMINATION_BANNER";
